### ISSUE TITLE
部分功能无法使用（Some functions cannot be used）

### ISSUE THREAD

**Issue by xiaoqingnian20** [kursatufukcoskun/7700HQ-Hackintosh-Macos-Opencore#1]
这款efi成功使我的7577运行了Big sur 但是部分功能仍旧无法实现
例如：HDMI无法输出 type-c无法使用 usb3.0无法使用，只可以插入2.0  oc引导win10休眠无效
This EFI successfully enabled my 7577 to run Big Sur, but some functions still could not be realized
For example, HDMI cannot output type-C, USB3.0 cannot be used, only 2.0 OC can be inserted to boot win10, and hibernation is invalid

**Comment by kursatufukcoskun** [comment]
- I'm using HDMI over USB Type-C (Dual monitor now)
- USB 3.0 working correctly.
- Sleep mode is working like a charm (Tried hibernatemode 0 and hibernatemode 3)
- Didn't understand this: "only 2.0 OC can be inserted to boot win10" I'm booting my Windows, Hackintosh and Linux from OC without any problem.

**Comment by xiaoqingnian20** [comment]
谢谢你的回复
-oc引导下，win10无法使用休眠功能，使用休眠功能开机无数据保存，无法恢复休眠之前的样子，休眠功能类似于重启，但是，确实这一点对没有太大影响。我使用 occ0.7.2 工具在boot勾选 DiscardHibernateMap也没有效果，可能是occ工具的问题。
-我使用usb确实存在问题，usb3.0直接插入，mac不识别，usb3.0缓慢插入才能成功识别，Hackintool 看到的是480mbps,我这边还没有尝试过定制usb。
-type-c只测试了usb功能，并且无法使用type-c的usb功能。

Thank you for your reply
-oc boot, Win10 can not use hibernation function, use hibernation function boot without data save, can not restore hibernation before the appearance, hibernation function is similar to restart, but, it does not have much impact on. I use the OCC0.7.2 tool to check the boot of DiscardHibernateMap and it does not work. It may be the problem of ocC tool.
- I do have problems using USB, USB3.0 directly inserted, MAC does not recognize, USB3.0 slowly inserted to successfully identify, Hackintool  saw 480Mbps, I have not tried to customize USB.
-type-c tests only the USB function, and the USB function of type-c cannot be used.
I hope you can give me some guidance on the above questions

**Comment by RoboCrafty** [comment]
Hey @kursatufukcoskun Could you tell me the exact specs of your laptop? I have the same one 7577 - i5 7700Hq

Also other than airdrop have you see any issues?
